name: Java

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        working-directory: ./java-springboot-final
        run: mvn --batch-mode -DskipTests package

      - name: Test
        working-directory: ./java-springboot-final
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Maven Tests
          path: ./java-springboot-final/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
